/*
 * @Author: error: error: git config user.name & please set dead value or install git && error: git config user.email & please set dead value or install git & please set dead value or install git
 * @LastEditTime: 2026-01-03 01:46:58
 * @LastEditors: px007
 * @ FilePath: Do not edit
 * sa~ka~na~
 */
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';
import fs from 'fs';
import { homedir } from 'os';

// Get the path to the SSL certificates generated by office-addin-dev-certs
function getHttpsConfig() {
  const certDir = resolve(homedir(), '.office-addin-dev-certs');
  const keyPath = resolve(certDir, 'localhost.key');
  const certPath = resolve(certDir, 'localhost.crt');

  // Check if certificates exist
  if (fs.existsSync(keyPath) && fs.existsSync(certPath)) {
    return {
      key: fs.readFileSync(keyPath),
      cert: fs.readFileSync(certPath),
    };
  }

  // Fallback to .cert directory (legacy location)
  const legacyKeyPath = resolve(process.cwd(), '.cert', 'key.pem');
  const legacyCertPath = resolve(process.cwd(), '.cert', 'cert.pem');

  if (fs.existsSync(legacyKeyPath) && fs.existsSync(legacyCertPath)) {
    return {
      key: fs.readFileSync(legacyKeyPath),
      cert: fs.readFileSync(legacyCertPath),
    };
  }

  console.warn('⚠️  SSL certificates not found. Run "npm run certs" to generate them.');
  console.warn('   Expected location: ' + certDir);
  return undefined;
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  const isDev = mode === 'development';

  return {
    plugins: [react()],

    resolve: {
      alias: {
        '@': resolve(__dirname, 'src'),
        '@components': resolve(__dirname, 'src/components'),
        '@core': resolve(__dirname, 'src/core'),
        '@adapters': resolve(__dirname, 'src/adapters'),
        '@services': resolve(__dirname, 'src/services'),
        '@hooks': resolve(__dirname, 'src/hooks'),
        '@store': resolve(__dirname, 'src/store'),
        '@types': resolve(__dirname, 'src/types'),
        '@utils': resolve(__dirname, 'src/utils'),
      },
    },

    server: {
      port: 3000,
      https: isDev ? getHttpsConfig() : undefined,
      headers: {
        'Access-Control-Allow-Origin': '*',
      },
      proxy: {
        // 使用代理解决CORS问题
        '/api': {
          target: 'https://cat.beijixingxing.com', // 目标API服务器
          changeOrigin: true, // 必须设置为true
          rewrite: path => path.replace(/^\/api/, ''), // 重写请求路径，去掉/api前缀
        },
      },
    },

    build: {
      outDir: 'dist',
      sourcemap: isDev,
      rollupOptions: {
        input: {
          main: resolve(__dirname, 'index.html'),
          taskpane: resolve(__dirname, 'taskpane.html'),
          commands: resolve(__dirname, 'commands.html'),
        },
        output: {
          manualChunks: {
            vendor: ['react', 'react-dom'],
            fluentui: ['@fluentui/react-components', '@fluentui/react-icons'],
            charts: ['chart.js', 'react-chartjs-2'],
          },
        },
      },
    },

    define: {
      'process.env.NODE_ENV': JSON.stringify(mode),
    },
  };
});
